title: GOOL
tagline: UCF Senior Design Project
description: >
  Senior Design Project at UCF by EE/CS students.
baseurl: ""

author:
  name: Lucas Rosa
  url: "lrosa007.github.io/GOOL"
  github_username: lrosa007

markdown: kramdown
