title: GOOL
tagline: Finding Dead People - UCF SD
description: >
  Senior Design Project at UCF by EE/CS students.
url: "https://github.com/lrosa007/GOOL"
baseurl: "/GOOL"

author:
  name: Dead Squad
  url: "https://www.youtube.com/watch?v=nMD_iZxpBiw"
  github_username: lrosa007

markdown: kramdown
